[build]
builder = "NIXPACKS"
buildCommand = "mvn -pl clamped-core,clamped-server -am package -DskipTests"

[deploy]
startCommand = "java -DDEMO_MODE=true -jar clamped-server/target/clamped-server-1.0.0-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
