package io.clamped;

import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Immutable snapshot of an error or flag event captured by the SDK.
 */
public final class ClampedEvent {

    public final Instant timestamp;       // set to Instant.now() at construction time

    // From ClampedConfig (set once at Clamped.init())
    public final String appName;          // ClampedConfig.appName
    public final String environment;      // ClampedConfig.environment

    // From EventContext (supplied by the caller via Clamped.add() / Clamped.flag())
    public final Severity severity;       // EventContext.severity (defaults to MEDIUM)
    public final String tag;              // EventContext.tag (optional, user-defined category)
    public final Map<String, Object> metadata; // EventContext.meta(...) key-value pairs

    // From the Exception (null for Clamped.flag() calls)
    public final String message;          // Exception.getMessage() or custom message string
    public final String exceptionClass;   // Exception.getClass().getName()
    public final String stacktrace;       // formatted stack trace from the exception

    // From CallerInfo (inspected from the call stack at capture time)
    public final String sourceFile;       // .java file where Clamped.add() was called
    public final int sourceLine;          // line number of the Clamped.add() call
    public final String sourceMethod;     // method name containing the Clamped.add() call

    // From the JVM / OS at capture time
    public final String threadName;       // Thread.currentThread().getName()
    public final String host;             // InetAddress.getLocalHost().getHostName()

    // Generated by Fingerprinter (for deduplication)
    public final String fingerprint;      // hash of exceptionClass + top stack frames (or message + tag)

    public ClampedEvent(
            String appName,
            String environment,
            Severity severity,
            String tag,
            String message,
            String exceptionClass,
            String stacktrace,
            Map<String, Object> metadata,
            String sourceFile,
            int sourceLine,
            String sourceMethod,
            String threadName,
            String host,
            String fingerprint) {
        this.timestamp = Instant.now();
        this.appName = appName;
        this.environment = environment;
        this.severity = severity;
        this.tag = tag;
        this.message = message;
        this.exceptionClass = exceptionClass;
        this.stacktrace = stacktrace;
        this.metadata = metadata != null
                ? Collections.unmodifiableMap(new LinkedHashMap<>(metadata))
                : Collections.emptyMap();
        this.sourceFile = sourceFile;
        this.sourceLine = sourceLine;
        this.sourceMethod = sourceMethod;
        this.threadName = threadName;
        this.host = host;
        this.fingerprint = fingerprint;
    }
}
